version: '1'
services:
  minecraft:
    image: marcermarc/minecraft:spigot_latest
    volumes:
      - ${APP_DATA_DIR}/data:/mnt/minecraft
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    stdin_open: true
    tty: true